-- MySQL Script generated by MySQL Workbench
-- Mon Nov 16 16:53:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Member` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Member` (
  `ID` VARCHAR(25) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `age` VARCHAR(10) NOT NULL,
  `sex` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `tel` INT NOT NULL,
  `major` VARCHAR(100) NULL,
  `membership` INT NULL,
  `date` DATE NOT NULL,
  `mon_cnt` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Book` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `book_title` VARCHAR(100) NOT NULL,
  `book_author` VARCHAR(100) NOT NULL,
  `book_company` VARCHAR(100) NULL,
  `book_image` BLOB NULL,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Board` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Board` (
  `user_ID` VARCHAR(25) NOT NULL,
  `content` VARCHAR(1500) NOT NULL,
  `input_type` INT NOT NULL,
  `suffix` INT NOT NULL,
  `content_title` VARCHAR(100) NOT NULL,
  `book_id` INT NULL AUTO_INCREMENT,
  PRIMARY KEY (`user_ID`, `content_title`),
  INDEX `book_id_idx` (`book_id` ASC) VISIBLE,
  UNIQUE INDEX `content_title_UNIQUE` (`content_title` ASC) VISIBLE,
  CONSTRAINT `ID`
    FOREIGN KEY (`user_ID`)
    REFERENCES `mydb`.`Member` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`Book` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Quiz` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Quiz` (
  `user_ID` VARCHAR(25) NOT NULL,
  `quiz_type` INT NOT NULL,
  `content_title` VARCHAR(100) NOT NULL,
  `quiz_id` INT NOT NULL AUTO_INCREMENT,
  `quiz_content` VARCHAR(1500) NOT NULL,
  `my_answer` VARCHAR(500) NULL,
  `correct_answer` VARCHAR(500) NOT NULL,
  `correct` INT NOT NULL,
  `quiz_date` DATE NOT NULL,
  `book_id` INT NOT NULL,
  INDEX `content_title_idx` (`content_title` ASC) VISIBLE,
  PRIMARY KEY (`quiz_id`, `user_ID`, `book_id`),
  UNIQUE INDEX `quiz_num_UNIQUE` (`quiz_id` ASC) VISIBLE,
  INDEX `book_id_idx` (`book_id` ASC) VISIBLE,
  UNIQUE INDEX `content_title_UNIQUE` (`content_title` ASC) VISIBLE,
  INDEX `ID_idx` (`user_ID` ASC) VISIBLE,
  CONSTRAINT `ID`
    FOREIGN KEY (`user_ID`)
    REFERENCES `mydb`.`Member` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `content_title`
    FOREIGN KEY (`content_title`)
    REFERENCES `mydb`.`Board` (`content_title`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`Book` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Score` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Score` (
  `user_ID` VARCHAR(25) NOT NULL,
  `quiz_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `score` INT NOT NULL,
  PRIMARY KEY (`user_ID`, `book_id`),
  INDEX `quiz_id_idx` (`quiz_id` ASC) VISIBLE,
  INDEX `book_id_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `quiz_id`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `mydb`.`Quiz` (`quiz_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`Book` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ID`
    FOREIGN KEY (`user_ID`)
    REFERENCES `mydb`.`Member` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
